apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
data:
  root-password: "cm9vdHBhc3M="
  user-pass: "ZGVtbw=="
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql
        resources:
          limits:
            cpu: "500m"
            memory: "500Mi"
        ports:
        - containerPort: 80
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: root-password
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: user-pass
